from ampdup import Song
from ampdup.parsing import parse_playlist


def test_song_from_lines():
    '''Create a playlist (list of Song) from lines.'''
    lines = [
        'file: Abney Park/Ancient World/Ancient World.m4a',
        'Last-Modified: 2018-02-06T22:36:06Z',
        'Artist: Abney Park',
        'Album: Ancient World',
        'Title: Ancient World',
        'Track: 4',
        'Genre: Steampunk',
        'Date: 2012',
        'Time: 270',
        'duration: 269.932',
        'Pos: 0',
        'Id: 8794',
        'file: Abney Park/The Death Of Tragedy/Downtrodden.mp3',
        'Last-Modified: 2018-02-07T09:45:05Z',
        'Artist: Abney Park',
        'Title: Downtrodden',
        'Album: The Death Of Tragedy',
        'Track: 9',
        'Date: 2005',
        'Genre: Steampunk',
        'Time: 314',
        'duration: 314.122',
        'Pos: 1',
        'Id: 8795',
        'file: GLaDOS/Portal/Still Alive.mp3',
        'Last-Modified: 2018-02-07T09:45:57Z',
        'Artist: GLaDOS',
        'Title: Still Alive',
        'Album: Portal',
        'Track: 1',
        'Date: 2007',
        'Genre: Soundtrack',
        'Time: 176',
        'duration: 176.489',
        'Pos: 2',
        'Id: 8796',
        'file: An Endless Sporadic/Sun of Pearl.mp3',
        'Last-Modified: 2018-02-07T09:45:06Z',
        'Artist: An Endless Sporadic',
        'Title: Sun of Pearl',
        'Genre: Progressive Rock',
        'Time: 305',
        'duration: 305.036',
        'Pos: 3',
        'Id: 8797',
    ]

    songs = [
        Song(
            file='Abney Park/Ancient World/Ancient World.m4a',
            last_modified='2018-02-06T22:36:06Z',
            time=270,
            duration=269.932,
            pos=0,
            id=8794,
            artist='Abney Park',
            albumartist='',
            title='Ancient World',
            album='Ancient World',
            genre='Steampunk',
            disc=None,
            track=4,
            date='2012'
        ),
        Song(
            file='Abney Park/The Death Of Tragedy/Downtrodden.mp3',
            last_modified='2018-02-07T09:45:05Z',
            time=314,
            duration=314.122,
            pos=1,
            id=8795,
            artist='Abney Park',
            albumartist='',
            title='Downtrodden',
            album='The Death Of Tragedy',
            genre='Steampunk',
            disc=None,
            track=9,
            date='2005'
        ),
        Song(
            file='GLaDOS/Portal/Still Alive.mp3',
            last_modified='2018-02-07T09:45:57Z',
            time=176,
            duration=176.489,
            pos=2,
            id=8796,
            artist='GLaDOS',
            albumartist='',
            title='Still Alive',
            album='Portal',
            genre='Soundtrack',
            disc=None,
            track=1,
            date='2007'
        ),
        Song(
            file='An Endless Sporadic/Sun of Pearl.mp3',
            last_modified='2018-02-07T09:45:06Z',
            time=305,
            duration=305.036,
            pos=3,
            id=8797,
            artist='An Endless Sporadic',
            albumartist='',
            title='Sun of Pearl',
            album='',
            genre='Progressive Rock',
            disc=None,
            track=None,
            date=None
        ),
    ]

    assert parse_playlist(lines) == songs
